version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-jwtapp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: jwtapp
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
